### ISSUE TITLE
Input missing in OsteoBioR Credibility intervals over time plot

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/OsteoBioR#59]
I attach renewal rates and isotope files for a model that I have run in OsteoBioR version 24.4.1.2 online. The model run in 134 minutes. The model had no issues as the ones reported previously in issue #57 this time.
[Isotopes.xlsx](https://github.com/user-attachments/files/16531806/Isotopes.xlsx)
[Renewal Rates.xlsx](https://github.com/user-attachments/files/16531807/Renewal.Rates.xlsx)

I am here reporting some things that should be fixed or improved in order to produce a plot that can be exported for publication. At the moment, I can only export a plot with a single individual at the time, given that it is not possible to set a range for the secondary axis, and I need to edit manually in through the svg file in inkscape.

Here my thoughts:

- [x] Legend position should also have options for being placed in the corners. Perhaps horizontal and vertical adjustment bars would fit better?
- Legend text has no box for actually changing the text (only title). I understand that the text is given by the name of the individual, but I think there should be chance of changing this more freely. What about an option where individual names are replaced by input names?
- [x] Texts should have an option for superscript and subscript parts (perhaps through /?). E.g. Bayesian Estimated δ13C (‰ - VPDB). -> https://github.com/Pandora-IsoMemo/shiny-tools/issues/27
- [x] Would add "Range detected" to the label "from data". 
- [x] I could not remove the secondary axis in the plot once I had selected it, even if I remove the second individual. I think there should be an option to clear the secondary axis.
- Instead, when selected, full label options should be available for secondary axis (currently only something called "Title" is available when a seconday axis is added).
- [x] If I add the secondary plot, by including the second individual in the Display, I cannot set a range for this secondary axis. This is very important in order to prepare a final plot with two or more individuals/isotopes.

@arunge

**Comment by arunge** [comment]
@isomemo Please let us discuss options here in our next meeting.

**Comment by arunge** [comment]
@CarloCocozza With [version 24.08.2](https://github.com/Pandora-IsoMemo/OsteoBioR/pull/62) on [OsteoBioR beta](https://isomemoapp.com/app/osteo-bio-r-beta), we implemented some of your points from [above](https://github.com/Pandora-IsoMemo/OsteoBioR/issues/59#issue-2453971830).  Please check details regarding the new version [here](https://github.com/Pandora-IsoMemo/OsteoBioR/pull/62#issue-2475489026).

Some points are not yet implemented, since this takes some time:

> - Legend text has no box for actually changing the text (only title). I understand that the text is given by the name of the individual, but I think there should be chance of changing this more freely. What about an option where individual names are replaced by input names?

-> _open_

> - Texts should have an option for superscript and subscript parts (perhaps through <sup>/</sup>?). E.g. Bayesian Estimated δ<sup>13</sup>C (‰ - VPDB). 

-> _in progress_

Regarding the legend texts: As you mentioned above, currently, the legend elements are simply the names of the models/individuals. Would it be an option to simply rename a model? First load the model (1) then save (2), and draw the plot with the renamed models (3)? By this we do have custom legend texts (4). This would save several effort. (I could add an help text that describes how to change legend texts.)
However, there is a bug right now: all saved models do occur in the legend, even when they are not selected for the plot. I will fix this!

Please, let me know if you have questions!

![image](https://github.com/user-attachments/assets/33fb0205-78b5-4104-837b-cb64f4416ba9)

**Comment by isomemo** [comment]
@arunge Carlo should comment on this!
@CarloCocozza please comment when possible!

**Comment by CarloCocozza** [comment]
@arunge thank you for your efforts! Please let me know when all changes have been implemented.

Regarding your question on legend text, I think I can surely follow your trick at the moment, but I believe that for the future something more immediate and user-friendly should be implemented. 

P.S. On a side note, I noticed that both OsteoBioR and IsoMemoApp (DSSM) have not been updated in months on their local version via docker.

**Comment by arunge** [comment]
@CarloCocozza With [version 24.09.0](https://github.com/Pandora-IsoMemo/OsteoBioR/pull/65) on [OsteoBioR beta](https://isomemoapp.com/app/osteo-bio-r-beta) it is now possible to use mathematical annotations in titles (pls check also the comment: https://github.com/Pandora-IsoMemo/shiny-tools/pull/26). This should solve the issue with sub- and superscripts. Please, feel free to test the updates.

Regarding, your request for a more user-friendly solution to change legend texts. I would suggest to keep this for later. For now, we have a solution how to solve this, but I will open a ticket and put it into the backlog.

Regarding
> P.S. On a side note, I noticed that both OsteoBioR and IsoMemoApp (DSSM) have not been updated in months on their local version via docker.

For updates of local versions via docker: Please _always_ update your local version manually as mentioned [here](https://github.com/Pandora-IsoMemo/OsteoBioR/wiki/Local-install-instructions#2-b-copy-paste-the-text-below-into-the-terminal-and-press-enter) with (e.g. for OsteoBioR beta version):
```
 docker pull ghcr.io/pandora-isomemo/osteo-bior:beta
```
before running the app with
```
docker run -p 3838:3838 ghcr.io/pandora-isomemo/osteo-bior:beta
```
  
I am closing here. Thanks for your patience! :pray:
